- hosts: master
  tasks:
  - name: download helm
    unarchive: 
      src: https://get.helm.sh/helm-v3.10.3-linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes
      extra_opts: [--strip-components=1]
        #  - name: download istioctl
        #    unarchive: 
        #      src: https://github.com/istio/istio/releases/download/1.7.3/istio-1.7.3-linux-amd64.tar.gz
        #      dest: /usr/local/bin
        #      extra_opts: 
        #      - --strip-components=2
        #      - --wildcards
        #      - '*/istioctl'
        #      remote_src: yes
  - name: download k9s
    ignore_errors: True
    unarchive: 
      src: https://github.com/derailed/k9s/releases/download/v0.26.7/k9s_Linux_x86_64.tar.gz
      dest: /usr/local/bin
      remote_src: yes
  - name: install istioctl 
    ignore_errors: True
    unarchive: 
      src: https://github.com/istio/istio/releases/download/1.16.1/istioctl-1.16.1-linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes
