#- hosts: master
- hosts: k8s_master_no
  user: root
  tasks:
  - name: Get token
    shell:  kubeadm token create --print-join-command
    register: token
    delegate_to: "{{ item }}"
    loop: "{{ groups['k8s_master_yes']}}"
  - name: get facts from master
    setup:
    delegate_to: "{{ item }}"
    loop: "{{ groups['k8s_master_yes']}}"
    delegate_facts: true
  - debug:
      msg: "{{ token }}"
  - name: Join Node
    shell: "{{ item  }}  --cri-socket /run/containerd/containerd.sock "
    with_items: "{{ token.results[0].stdout_lines }}"



