- hosts: nodes
  tasks:
  - name: Get token
    shell:  kubeadm token create --print-join-command
    register: token
    delegate_to: "{{ item }}"
    loop: "{{ groups['master']}}"
  - name: Join Node
    shell: "{{ item  }}"
    with_items: "{{ token.results[0].stdout_lines }}"



